---
title: "International Environmental Treaties"
author: "Thuy Nguyen"
date: "February 7, 2020"
output: html_document
---

Hi reviewers! Please allow me to work on this for 2 more days (Thurs and Fri). There's still too many things I need to figure out.  I'll let you know when I'm more ready. Thank you for your understanding. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(here)
library(tidyverse)
library(ggplot2)
library(gghighlight)
library(colorblindr)

```


```{r load data}
iea <- import(here("data", "iea_measonly.dta"))

```


```{r}

iea %>% 
  count(subject_group) %>% 
  ggplot(aes(fct_reorder(subject_group), n), fill = subject_group) +
           geom_bar(position = "dodge") +
  facet_wrap(~agreement_type) +
  coord_flip() +
  guides(fill = FALSE) +
  labs(
    x = "Type of treaty group",
    y = "Number of treaties",
    title = "Type of treaties by subjects"
  )
```


``` {r}
iea %>% 
  select("tsig_yr", "subject_group", "region_continent") %>% 
  filter(region_continent == c("Africa", "Asia", "Central America", 
                              "Europe", "North America", "Oceania",
                              "South America")) %>% 
  # arrange(tsig_yr) %>% 
  # group_by(subject_group) %>% 
  ggplot(aes(subject_group, fill = subject_group)) +
  geom_bar(position = "dodge") +
  coord_flip() +
  guides(fill = FALSE) +
  facet_wrap(~region_continent) + 
  scale_color_OkabeIto() +
  labs(
    x = "Type of treaty group",
    y = "Number of treaties",
    title = "Type of treaties signed by continent"
  )

# need to get the map somewhere

```

# From signature to entry into force


```{r}
dp3 <- iea %>% 
  select("subject_group", "tsig_yr", "teif_yr") %>% 
  mutate(into_force = teif_yr - tsig_yr) %>% 
  # mutate(ifelse(into_force > 20, "Not ratified", "")) # how to group the treaties nevered fot rarified (into_force > 20)
  filter(into_force < 20) %>% 
  filter(subject_group != "Uncoded")  %>% 
  filter(subject_group != "")
  # group_by(into_force) 
  # mutate(subject_group = fct_reorder(subject_group, into_force)) %>% 
  
ggplot(dp3, aes(fct_reorder(subject_group, into_force), into_force)) + # why fct_reorder doesn't work here?
  geom_col(position = "dodge") + # not sure what the dodge does here. I just got weird result without dodge. 
  coord_flip() +
  scale_fill_viridis_d() +
  labs(
    x = "Type of treaty group",
    y = "Number of years from signature to entry into force",
    title = "Years from signature to entry into force across type of environmental treaties",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  )

  
```

