---
title: "Multilateral Evironmental Agreements 1857 - 2016"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(here)
library(tidyverse)
library(ggplot2)
library(gghighlight)
library(colorblindr)
library(rnaturalearth)
library(gt)
library(reactable)
library(gganimate)
library(patchwork)
library(ggridges)
library(flexdashboard)
```


Data  {data-icon="fa-table"}
=======================================

Column {data-width=500}
-----------------------------------------------------------------------

### Original Data

```{r echo = FALSE}
data <- import(here("data", "iea_measonly.dta"))
reactable(data)
```

-----------------------------------------------------------------------

### Data used for visualization


```{r echo = FALSE}
d <- data %>%
  select(mitch_id, tsig_yr, teif_yr, subject_category, lineage)


reactable(d, 
          defaultSortOrder = "desc",
          filterable = TRUE, minRows = 10,
          columns = list(
  mitch_id = colDef("ID"),
  tsig_yr = colDef("Year signed"),
  teif_yr = colDef("Year ratified"),
  subject_category = colDef("Subject"),
  lineage = colDef("Lineage")
))


```

```{r}

```


### Agreements were ratified in the same year they were signed 

```{r echo = FALSE}
sameyear = function(...) return(349)
ratifysameyear = sameyear()
valueBox(ratifysameyear, icon = "fa-clock-o")

```

### Agreements never got ratified 

```{r echo = FALSE}
never = function(...) return(141)
neverratify = never()
valueBox(neverratify, icon = "fa-ban")

```


### Years on average from signed to ratified 

```{r echo = FALSE}
meanyear = function(...) return(2.2)
gapyear = meanyear()
valueBox(gapyear, icon = "fa-pause")

```





Visualization {data-icon="fa-signal"}
=======================================


### Chart A: Change in number of agreements over time

```{r echo = FALSE}
library(lubridate)
species <- d %>% 
  select(subject_category, tsig_yr) %>% 
  filter(subject_category == "Species") %>% 
  group_by(tsig_yr) %>% 
  add_count() %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) 

pollution <- d %>% 
  select(subject_category, tsig_yr) %>% 
  filter(subject_category == "Pollution") %>% 
  group_by(tsig_yr) %>% 
  add_count() %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) 

d_num <- d %>% 
  select(tsig_yr, subject_category) %>% 
  group_by(tsig_yr) %>%
  add_count()  %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr)))

event <- tibble(date = lubridate::mdy(c("December 31, 1972")),
                text = c("UN Conference on Human Environment"))


 change_number <- d %>% 
  group_by(tsig_yr) %>%
  add_count()  %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) %>% 
  # pivot_wider(names_from = subject_category, # doesn't work
  #             values_from = n
  #             )
  ggplot(aes(date, n)) +
  geom_line(color = "gray40") +
  # geom_line(data = filter(d, subject_category == "Species", 
  #                         aes(x = date, 
  #                         y = n))) + # why this doesn't work?
  geom_line(data = species, color = "#C55644") +
  geom_line(data = pollution, color = "purple") +
  geom_vline(aes(xintercept = date), 
             data = event,
             color = "gray40",
             lty = "dashed") +
  geom_text(aes(x = date, y = 45, label = text),
            data = event,
            color = "black",
            nudge_x = 2) +
  labs(
    x = "",
    y = "Number of Agreements Signed",
    title = "Multilateral Environmental Agreements Signed between 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. \n International Environmental Agreements Database Project (Version 2020.1). \n http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) +
  theme_minimal() 
 # transition_reveal(tsig_yr) why this doesn't work?
change_number
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Change in type of agreements over time

```{r echo = FALSE, fig.width=12, fig.height=10}

bp_theme <- function(...) {
  theme_minimal(...) +
    theme(panel.grid.major.y = element_blank(), 
          panel.grid.minor.x = element_blank(), 
          panel.grid.major.x = element_line(color = "gray80"))
          # plot.title.position = "plot") # "plot.title.position" is not a valid theme element name. 
}

d_at <- data %>% 
  select(tsig_yr, agreement_type) %>% 
  group_by(tsig_yr, agreement_type) %>% 
  count() 

d_at%>% 
  ggplot(aes(tsig_yr, n, fill = agreement_type)) +
  geom_ribbon(aes(ymin = 0,
                  ymax = n,
                  fill = agreement_type,
                  color = agreement_type),
              alpha = 0.4) +
  scale_fill_brewer("agreement_type", palette = "Set2")  +
  scale_color_brewer("agreement_type", palette = "Set2") +
  facet_wrap(~agreement_type) +
   labs(
    x = "",
    y = "Number of Agreements Signed",
    title = "Environmental Agreements Signed by Type between 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) +
  guides(fill = FALSE, color = FALSE) +
  theme_minimal() 

```

### Chart C: Change in subject of agreements over time

```{r echo = FALSE, fig.width=12, fig.height=10}
bf45 <- d %>% 
  filter(tsig_yr < 1945) %>% 
group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue") +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -1,
            size = 2) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Number of Agreements by Subject \n
    Before 1945"
  )

# highlight new subjects in this period
newsubject4570 <- d %>% 
  filter(tsig_yr > 1944 &
          tsig_yr < 1972) %>%
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

bt4570 <- d %>% 
  filter(tsig_yr > 1944 &
          tsig_yr < 1972) %>% 
  group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue", 
           alpha = .5) +
  geom_col(data = newsubject4570,
           fill = "#C55644") +
  scale_fill_OkabeIto() +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -2, # hard to get the right value. 
            size = 2) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Between 1945 - 1972"
  ) 


newsubject70001 <- d %>% 
  filter(tsig_yr > 1971 &
        tsig_yr < 2000) %>% 
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

newsubject70002 <- d %>% 
  filter(tsig_yr > 1971 &
        tsig_yr < 2000) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>%
  filter(subject_category == "Other") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

bt7000 <- d %>%  
  filter(tsig_yr > 1971 &
        tsig_yr < 2000) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>% 
  group_by(subject_category) %>% 
  count(subject_category)  %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue",
           alpha = .5) +
  geom_col(data = newsubject70001,  
           fill = "#C55644",
           alpha = .5) +
  geom_col(data = newsubject70002,
           fill = "purple") +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -6,
            size = 2) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Between 1972 - 2000"
  )

newsubject20001 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

newsubject20002 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>%
  filter(subject_category == "Other") %>% 
  group_by(subject_category) %>% 
  count(subject_category)



af2000 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>% 
  group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue", 
           alpha = .5) +
  geom_col(data = newsubject20001,
           fill = "#C55644",
           alpha = .5) +
  geom_col(data = newsubject20002,
           fill = "purple",
           alpha = .5) +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -1, 
            size = 2) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "After 2000", 
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) 
  
bf45 + bt4570 + bt7000 + af2000
```


Concepts {data-icon="fa-signal"}
=======================================


### Chart A

```{r}


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```
