---
title: "Multilateral Environmental Agreement 1857 - 2016"
subtitle: "⚔<br/>with xaringan"
author: "Thuy Nguyen"
institute: "Universifty of Oregon"
date: "2020/11/03"
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      countdown: 60000
---


```{r eval=FALSE, tidy=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(here)
library(tidyverse)
library(ggplot2)
library(gghighlight)
library(colorblindr)
library(rnaturalearth)
library(gt)
library(reactable)
library(gganimate)
library(patchwork)
library(ggridges)

```

--

# R Plots

```{r , fig.height=4, dev='svg'}
data <- import(here("data", "iea_measonly.dta")) 

d <- data %>% 
  select(mitch_id, tsig_yr, teif_yr, subject_category, lineage)

# Subset of data used for the following demonstrations
d_table <- d %>%
  arrange(tsig_yr) %>%
  gt() %>%
  cols_label(tsig_yr = "Year signed",
             teif_yr = "Year ratified",
             subject_category = "Subject",
             lineage = "Lineage") %>%
  tab_header(title = "Mutilateral Environmental Agreements 1857 - 2016") %>%
  tab_source_note(source_note = md("Data from [Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project](http://iea.uoregon.edu/)"))

```

---
## Change in number of agreements over time


```{r, fig.width=8, eval = FALSE }
library(lubridate)

species <- d %>% 
  select(subject_category, tsig_yr) %>% 
  filter(subject_category == "Species") %>% 
  group_by(tsig_yr) %>% 
  add_count() %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) # to transfer the x as numbers into date
  

pollution <- d %>% 
  select(subject_category, tsig_yr) %>% 
  filter(subject_category == "Pollution") %>% 
  group_by(tsig_yr) %>% 
  add_count() %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) 

event <- tibble(date = lubridate::mdy(c("December 31, 1972")),
                text = c("UN Conference on Human Environment"))

 d %>% 
  group_by(tsig_yr) %>%
  add_count()  %>% 
  mutate(date = mdy(paste0("01-01-", tsig_yr))) %>% 
  ggplot(aes(date, n)) +
  geom_line(color = "gray40") +
  geom_line(data = species, color = "#C55644") +
  geom_line(data = pollution, color = "purple") +
  geom_vline(aes(xintercept = date), 
             data = event,
             color = "gray40",
             lty = "dashed") +
  geom_text(aes(x = date, y = 45, label = text),
            data = event,
            color = "black",
            nudge_x = 2) +
  labs(
    x = "",
    y = "Number of Agreements Signed",
    title = "Multilateral Environmental Agreements Signed between 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) +
  theme_minimal() 
 # transition_reveal(tsig_yr) why this doesn't work?
```

    
---
## Change in type of agreements over time

```{r Agreement type, eval = FALSE}

bp_theme <- function(...) {
  theme_minimal(...) +
    theme(panel.grid.major.y = element_blank(), 
          panel.grid.minor.x = element_blank(), 
          panel.grid.major.x = element_line(color = "gray80"))
          # plot.title.position = "plot") # "plot.title.position" is not a valid theme element name. 
}

d_at <- data %>% 
  select(tsig_yr, agreement_type) %>% 
  group_by(tsig_yr, agreement_type) %>% 
  count() 


option1 <- d_at%>% 
  ggplot(aes(tsig_yr, n, fill = agreement_type)) +
  geom_ribbon(aes(ymin = 0,
                  ymax = n,
                  fill = agreement_type,
                  color = agreement_type),
              alpha = 0.4) +
  scale_fill_brewer("agreement_type", palette = "Set2")  +
  scale_color_brewer("agreement_type", palette = "Set2") +
  facet_wrap(~agreement_type) +
   labs(
    x = "",
    y = "Number of Agreements Signed",
    title = "Environmental Agreements Signed by Type between 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) +
  guides(fill = FALSE, color = FALSE) +
  theme_minimal() 


option2 <- d_at %>% 
 ggplot(aes(tsig_yr, agreement_type)) +
  geom_density_ridges(color = "white",
                                fill = "#A9E5C5") +
  xlim(1857,2016) +
  labs(
    x = "",
    y = "",
    title = "Environmental Agreements Signed by type 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) +
  guides(fill = FALSE, color = FALSE) +
  theme_minimal(base_size = 15) 

option3 <- d_at %>% 
ggplot(aes(tsig_yr, agreement_type)) +
  geom_tile(aes(fill = n),
            color = "gray90") +
  scale_fill_viridis_c(option = "magma") +
  # coord_fixed() +     coord_fixed make the fig high too small
  theme(legend.position = "bottom", # why not?
        legend.direction = "horizontal", # how to get the plot bigger? fig.with and fig.heigh don't help
        legend.key.size = unit(1, 'cm'),
        legend.key.height = unit(0.5,"cm")) +
  bp_theme() +
  labs(
    x = "",
    y = "Type of Agreement",
    title = "Environmental Agreements Signed by Type between 1857 - 2016",
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  )

option1 # the best?
option2
option3 # my be not
```


--

## Change in subject of agreements over time
```{r fig.width=10, fig.height=10, eval = FALSE}
# Type of treaty in each historical period
# Problem: not in the same scale

bf45 <- d %>% 
  filter(tsig_yr < 1945) %>% 
group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue") +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -1,
            size = 4) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Number of Agreements by Subject Before 1945"
  )

# highlight new subjects in this period
newsubject4570 <- d %>% 
  filter(tsig_yr > 1944 &
          tsig_yr < 1970) %>%
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

bt4570 <- d %>% 
  filter(tsig_yr > 1944 &
          tsig_yr < 1970) %>% 
  group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue", 
           alpha = .5) +
  geom_col(data = newsubject4570,  
           fill = "#C55644") + 
  scale_fill_OkabeIto() +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -2, # hard to get the right value. 
            size = 4) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Number of Agreements by Subject Between 1945 - 1970"
  ) 


newsubject70001 <- d %>% 
  filter(tsig_yr > 1969 &
        tsig_yr < 2000) %>% 
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

newsubject70002 <- d %>% 
  filter(tsig_yr > 1969 &
        tsig_yr < 2000) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>%
  filter(subject_category == "Other") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

bt7000 <- d %>%  
  filter(tsig_yr > 1969 &
        tsig_yr < 2000) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>% 
  group_by(subject_category) %>% 
  count(subject_category)  %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue", 
           alpha = .5) +
  geom_col(data = newsubject70001,  # want to highlight new subjects
           fill = "#C55644",
           alpha = .5) +
  geom_col(data = newsubject70002,
           fill = "purple") +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -6,
            size = 4) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Number of Agreements by Subject Between 1970 - 2000"
  )

newsubject20001 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  filter(subject_category == "Ocean" | 
         subject_category == "General" |
         subject_category == "Habitat") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

newsubject20002 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>%
  filter(subject_category == "Other") %>% 
  group_by(subject_category) %>% 
  count(subject_category)

af2000 <- d %>% 
  filter(tsig_yr > 1999) %>% 
  mutate(subject_category = ifelse(subject_category == "", "Other", subject_category)) %>% 
  group_by(subject_category) %>% 
  count(subject_category) %>% 
ggplot(aes(fct_reorder(subject_category,n), n))+
  geom_col(fill = "cornflowerblue", 
           alpha = .5) +
  geom_col(data = newsubject20001,  
           fill = "#C55644",
           alpha = .5) +
  geom_col(data = newsubject20002,  
           fill = "purple",
           alpha = .5) +
  geom_text(aes(subject_category, n, label = n),
            # nudge_y = -1, 
            size = 4) +
  coord_flip() +
  bp_theme(base_size = 10) +
  guides(fill = FALSE, color = FALSE) +
  labs(
    x = "",
    y = "",
    title = "Number of Agreement by Subject After 2000", 
    caption = "Data from Ronald B. Mitchell. 2002-2020. International Environmental Agreements Database Project (Version 2020.1).
Available at: http://iea.uoregon.edu/ Date accessed: 26 February 2020"
  ) 
bf45 + bt4570 + bt7000 + af2000
```
  

---
